# Dynamic programming 

### 1. top down : recursive call 
### 2. top down with memoization 
### 3. bottom up 

## Rod cutting Problem 
 recursive formula :  $r_n = \max(\max_{1 \le i \le {n - 1}} (p_i + r_{n-i}), p_n)$

- top down 
    
    recursive top down 방식 ; inefficient  
    
    running time : $T(n) = 2^n$

In [1]:
# 길이 n 짜리 rod에 대해 cutting했을때의 최대 가격을 q로 저장 
def cutrod(p,n):
    if n == 0:
        return 0
    q = -float('inf')
    for i in range(1,n+1):
        q = max(q, p[i] + cutrod(p,n-i))  # 모든 경우를 계산하여  optimal 한경우를 q 로 저장 
    return q

- top down with memoization 방식 ; checking 한 후(저장된 값이 있는지), 저장 값이 없다면 recursive call을 통해 subproblem 푼다.
   
  running time: $ T(n) = O(n^2) $ 
  ,because entry size n, choosing n => $ n^2 $
    

In [2]:
# top down with memoization 
# r[길이] array에 최대 가격을 메모한다. 

def cutrod1_memo(p,n):
    # let r[0 .. n] be a new array 
    r = [0 for _ in range(n + 1)]
    
    for i in range(0,n+1):
        r[i] = -float('inf')    # memo 할 r[i] 값을 초기화 한다. 
    return memo_topdown(p,n,r)  # r[] 에 memo를 하며 topdown 방식으로 문제를 푼다. 

#subroutine으로 이용
def memo_topdown(p,n,r):
    if r[n] >= 0:
        return r[n]
    if n==0:
        q = 0
        
    # 저장된값이 없다면,
    else:
        q = -float('inf')
        for i in range(1,n+1):
            q = max(q, p[i] +  memo_topdown(p,n-i,r))    # 계산을 하여 최대값을 q로 지정 여기서 memo한것들은 O(1)시간에 된다.
            
    # 계산 후 저장        
    r[n] = q
    return q

- bottom up 방식 ; subproblem을 먼저 풀고, 이를 이용한다. memoization 을 통해 할 수 있다. 

  a problem of size is smaller than subproblem of size j ,if $ i \le j $ 
  
  running time:  $ T(n) = O(n^2) $ , because doubly nested loop  $ i \le j \le n $

In [3]:
def cutrod2_memo(p,n):
    # let r[0 .. n] be a new array 
    r = [None for _ in range(n + 1)]
    r[0] = 0
    
    # subproblem에서 부터 total sol을 이끌어낸다. 
    for j in range(1,n+1):
        q= -float('inf')
        # i <= j 가 되도록 한다. 또한, r[j - i] 를 통해 subproblem의 solution을 이용 
        for i in range(1,j+1):
            q = max(q, p[i]+ r[j-i])  # Line 10~11 : subproblem size of j 를 푸는 과정(i = 1 .. j 경우의수에 대해 optimal값 찾음)
        r[j] = q
    return r[n]
        

In [4]:
p = [-1,1,5,8,9,10,17,17,20,24,30]     # python 은 array 가 p[0] ~ p[10] 까지 있으므로 
for i in range(1, 11):      # i =  length 를 의미 
    sol1 = cutrod(p,i)
    sol2 = cutrod1_memo(p,i)
    sol3 = cutrod2_memo(p,i)
    print(sol1, "top down ")
    print(sol2, "topdown with memo ")
    print(sol3, "bottom up ")

1 top down 
1 topdown with memo 
1 bottom up 
5 top down 
5 topdown with memo 
5 bottom up 
8 top down 
8 topdown with memo 
8 bottom up 
10 top down 
10 topdown with memo 
10 bottom up 
13 top down 
13 topdown with memo 
13 bottom up 
17 top down 
17 topdown with memo 
17 bottom up 
18 top down 
18 topdown with memo 
18 bottom up 
22 top down 
22 topdown with memo 
22 bottom up 
25 top down 
25 topdown with memo 
25 bottom up 
30 top down 
30 topdown with memo 
30 bottom up 


### Hw
Length  | 1  2  3  4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  20

Price    | 1  5  8  9  10  17  17  20  24  25  25  30  32  33  35  37  37  40  42  43


1.	최대가 된 가격을 출력
2.	자른 막대의 길이를 출력
ex) (12, 5, 3)
Hint) 1-D array 하나를 더 써서 가능

In [5]:
def extended_bottom_up_rod_cut(p,n):
    r = [0 for _ in range(n + 1)]   # r[] 배열의 초기값 
    s = [0 for _ in range(n + 1)]
    for j in range(1, n+1):
        q = -1
        for i in range(1, j+1):
            if q < p[i] + r[j-i]:
                q = p[i] + r[j-i]
                s[j] = i           # price 가 최대가 된 지점에서의 length i 를 s[j]에 저장
        r[j] = q                   # (j길이의 토막에서  i길이의 토막을 잘랐을때, 최대가됨)
        
    return r,s                    # r[j]에는 size j 의 토막 optimal price info 가 들어있고, 
                                  #s에는 r[j]를 만들때 i길이와 j-i 길이로 분해하는 값을 저장: s[j] = i 
                   

def print_cut_rod_solution(p,n):
    r,s = extended_bottom_up_rod_cut(p,n)
    while n > 0:
        print(s[n])
        n = n - s[n]

In [6]:
p = [-1,1,5,8,9,10,17,17,20,24,25,25,30,32,33,35,37,37,40,42,43]
r,s = extended_bottom_up_rod_cut(p,(len(p)-1))
print(r)
print(s)

print("1th problem. ", (len(p)-1), "길이의 토막을 나눌때 최대가 된가격:  ", r[(len(p)-1)] )
print("2th problem.  ", "나무토막을 나눈 각각의 길이 ")
print_cut_rod_solution(p,(len(p)-1))


[0, 1, 5, 8, 10, 13, 17, 18, 22, 25, 27, 30, 34, 35, 39, 42, 44, 47, 51, 52, 56]
[0, 1, 2, 3, 2, 2, 6, 1, 2, 3, 2, 2, 6, 1, 2, 3, 2, 2, 6, 1, 2]
1th problem.  20 길이의 토막을 나눌때 최대가 된가격:   56
2th problem.   나무토막을 나눈 각각의 길이 
2
6
6
6


## Matrix-chain multiplication 
: matrix multiplication 할때, parenthesization 을 어떻게 효율적으로 할 것인가?

the number of parenthesization : $ P(n) = \sum_{k=1}^{n-1} P(k) \cdot P(n-k) , if ( n \ge 2 \ )$

let m[i,j] = cost of parenthesization A[i .. j ] , when scalar multiplication 
,where each matrix $A_i$ is $p_{i-1} \times p_i$     , that is, $A_i$'s  numbers of col : $ p_i $  

note that the cost of 
$( A_i \times  .. \times A_{k} ) \times (A_{k+1} \times .. \times A_{j} )$
is  that  $ m[i,k] + m[k+1,j] + p_{i-1}p_k p_j $ 

recursive formula :  $m[i,j] = \min_{i \le k < j}(m[i.k] + m[k+1,j] + p_{i-1} p_k p_j ) \ , \ if \ i < j $


 - top down 
 
 for $m[1,n],  k = 1 .. n-1$
 
  
 $ from \ T(n) \ge 1 +  \sum_{k=1}^{n-1}(T(k) + T(n-k) + 1) ,$ 
 
 
 $$
 T(n) = Ω(2^n)
 $$

In [7]:
# 1 .recursive 
def recursive_matrix_chain(p,i,j,m):
    if i==j:
        return 0
    
    # minimum 값을 m[i][j] 에 저장하는데, 똑같은 계산을 반복 하므로  inefficient 하게 계산 
    m[i][j] = float('inf')
    for k in range(i, j):
        q = recursive_matrix_chain(p,i,k,m) + recursive_matrix_chain(p,k+1,j,m) + p[i-1]*p[k]*p[j]
        if q < m[i][j]:
            m[i][j] = q
        
    return m[i][j]

- topdown with memo
$$
    T(n) = O(n^3)
$$
because entry $n^2$, choosing among $n$ 

In [8]:
# 2. top down with memo 
import numpy as np

def memoized_matrix_chain(p):
    n = len(p) - 1 
    m = np.ones([len(p),len(p)])*float('inf') # memo 할 matrix 형성 
    
    return lookup_chain(m,p,1,n) 

def lookup_chain(m,p,i,j):         # topdown with memo 를 통해 A[i .. j] 에 대한 cost를 구해주는 함수 
    if m[i][j] < float('inf'):
        return m[i][j]
    if i == j:
        m[i][j] = 0
    else:
        for k in range(i, j):
            q = lookup_chain(m,p,i,k) + lookup_chain(m,p,k+1,j) + p[i-1]*p[k]*p[j]
            if q < m[i][j]:
                m[i][j] = q
    return m[i][j]

- bottom up 
$$
    T(n) = O(n^3)
$$
three nested loop 

In [9]:
# 3. bottom up approach 
def matrix_chain_order(p):
    n = len(p) - 1 
    m = np.zeros([len(p),len(p)])
    s = np.zeros([len(p),len(p)])
    for i in range(1,n+1):        # i = j, l = 1 일때 
        m[i][i] = 0
        
    # three nested loop : i < j =< n 
    for l in range(2,n+1):              # l = j - i + 1   (chain length 를 의미)
        for i in range(n-l+2):          
            j = i + l - 1 
            m[i][j] = float('inf')
            for k in range(i,j):
                q = m[i][k] + m[k+1][j] + p[i-1]*p[k]*p[j] 
                if q < m[i][j]:
                    m[i][j] = q
                    # when we have optimal sol ?  s[i][j] = k !  
                    s[i][j] = k 
    return m,s

problem : $  A_1 \times  .. \times A_{6} $  
information p[i] = $A_i$'s column #

In [10]:
import numpy as np
p = [30,35,15,5,10,20,25]
m = [[0 for col in range(len(p))] for row in range(len(p))]
# recursive call 을 할때, call 은 (1,6) 부터 하지만, 계산은 overlapping 되며 subproblem 부터 하게 된다. 

print(" recursive method")
print(recursive_matrix_chain(p,1,6,m))
print(np.array(m))

# Top down with memoization 
print(" top down method")
print(memoized_matrix_chain(p))

# bottom up approach 
print(" bottom up method")
[M,S]= matrix_chain_order(p)
print(M)
print(S)

 recursive method
15125
[[    0     0     0     0     0     0     0]
 [    0     0 15750  7875  9375 11875 15125]
 [    0     0     0  2625  4375  7125 10500]
 [    0     0     0     0   750  2500  5375]
 [    0     0     0     0     0  1000  3500]
 [    0     0     0     0     0     0  5000]
 [    0     0     0     0     0     0     0]]
 top down method
15125.0
 bottom up method
[[    0. 26250. 27000. 11625. 12875. 15125.     0.]
 [    0.     0. 15750.  7875.  9375. 11875. 15125.]
 [    0.     0.     0.  2625.  4375.  7125. 10500.]
 [    0.     0.     0.     0.   750.  2500.  5375.]
 [    0.     0.     0.     0.     0.  1000.  3500.]
 [    0.     0.     0.     0.     0.     0.  5000.]
 [    0.     0.     0.     0.     0.     0.     0.]]
[[0. 0. 0. 0. 3. 3. 0.]
 [0. 0. 1. 1. 3. 3. 3.]
 [0. 0. 0. 2. 3. 3. 3.]
 [0. 0. 0. 0. 3. 3. 3.]
 [0. 0. 0. 0. 0. 4. 5.]
 [0. 0. 0. 0. 0. 0. 5.]
 [0. 0. 0. 0. 0. 0. 0.]]


## Longest common subsequence problem 
: LCS 를 찾아라

let  $c[i,j]$ be the length of an LCS of the $X_i \ and \ Y_j $

>property of Optimal substructure 

>let $Z = [z_1, z_2, ... ,z_k]$,
    $X = [z_1, z_2, ... ,z_m]$,
    $Y = [z_1, z_2, ... ,z_n]$,  
    where $k = c[m,n]$
 
> if $x_m = y_n $, then $z_k = x_m = y_n$ and $Z_{k-1}$ is an LCS of $X_{m-1}$ and $Y_{n-1}$  
> if $x_m \ne y_n $, then $z_k \ne x_m$ implies that $Z$ is an LCS of $X_{m-1}$ and $Y$  
> if $x_m \ne y_n $, then $z_k \ne y_n$ implies that $Z$ is an LCS of $X$ and $Y_{n-1}$  

reculsive formula : 

$$
c[i,j] = \left \{ 
\begin{matrix}
c[i-1, j-1] + 1 & \text{if}~ i, j > 0  \text{ and } x_i = y_j, \text{: case 1 }\\
\max(c[i, j-1], c[i-1, j]) & \text{if}~ i, j > 0 \text{ and } x_i \ne y_j \text{ : case 2 }\\
\end{matrix}\right.
$$                       

 - bottom up 
 $$
 T(n) = O(mn), \ for \ inputs \ : \ X[1..m], Y[1..n]
 $$
 
 in order to solve c[m][n],
 
 we have to fill up $mn$ entries, where each entry takes O(1) time
 
 because choosing between 2 previous subproblem 

In [11]:
# bottom up approach ; three nested loop 
def LCS_LENGTH(X, Y):
    m = len(X)-1
    n = len(Y)-1
    c = [[None for col in range(len(Y))] for row in range(len(X))]
    
    for i in range (1, m+1):
        c[i][0]= 0
    
    for j in range (0, n+1):
        c[0][j] = 0
     
    for i in range(1,m+1):
        for j in range(1,n+1):
            if X[i]==Y[j]:                    # case 1
                c[i][j] = c[i-1][j-1]+1
                #b[i][j] = "↖" 
            else:                            # case 2 ; X[i] != Y[j]
                c[i][j] = max(c[i-1][j], c[i][j-1])
                #b[i][j] = "↑"  , if c[i-1][j] >= c[i][j-1]
                #b[i][j] = "←"  , if c[i-1][j] < c[i][j-1]
                
                
    return c

In [12]:
def PRINT_LCS(c, X, Y, i, j):
    if i==0 or j==0:
        return 
    if X[i]==Y[j]:                            #b[i][j] = "↖"
        PRINT_LCS(c, X, Y, i - 1, j - 1)
        print(X[i])
    elif c[i - 1][j] >= c[i][j - 1]:          #b[i][j] = "↑" 
        PRINT_LCS(c, X, Y, i - 1, j)
    else:                                     #b[i][j] = "←" 
        PRINT_LCS(c, X, Y, i, j - 1)

In [13]:
import numpy as np

X = [-1,1,0,0,1,0,1,0,1]        # 크기를 1 값부터 m 값 까지 정해야 하므로 index 0 에 -1 값 을 넣었다.
Y = [-1,0,1,0,1,1,0,1,1,0]
C1 = LCS_LENGTH(X,Y)   # c[8][9] = 6 ; 길이 6 의 LCS를 찾음 
PRINT_LCS(C1, X, Y, len(X)-1, len(Y)-1) # index 0 값을 무시해야 하므로 길이 - 1 을 해야함 
print(np.array(C1))   

X2 = [-1,'A','B','C','B','D','A','B']
Y2 = [-1,'B','D','C','A','B','A']
C2 = LCS_LENGTH(X2,Y2)    # c[7][6] = 4 ; 길이 4 의 LCS를 찾음 
PRINT_LCS(C2, X2, Y2, len(X2)-1, len(Y2)-1)
print(np.array(C2))

1
0
0
1
1
0
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 1 1 1]
 [0 1 1 2 2 2 2 2 2 2]
 [0 1 1 2 2 2 3 3 3 3]
 [0 1 2 2 3 3 3 4 4 4]
 [0 1 2 3 3 3 4 4 4 5]
 [0 1 2 3 4 4 4 5 5 5]
 [0 1 2 3 4 4 5 5 5 6]
 [0 1 2 3 4 5 5 6 6 6]]
B
C
B
A
[[0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1]
 [0 1 1 1 1 2 2]
 [0 1 1 2 2 2 2]
 [0 1 1 2 2 3 3]
 [0 1 2 2 2 3 3]
 [0 1 2 2 3 3 4]
 [0 1 2 2 3 4 4]]


## Optimal binary search trees Problem 

> [recall] Binary Search Tree properties  

>The left subtree of a node contains only nodes with keys lesser than the node’s key.

>The right subtree of a node contains only nodes with keys greater than the node’s key.

>The left and right subtree each must also be a binary search tree.

>There must be no duplicate nodes.

: given each possibility of seaching nodes 
  
  $p_i$ : prob of searching internal nodes($k_i, i = 1, ..., n $)  
  
  $q_i$ : prob of searching internal nodes($d_i, i = 0, ..., n$)
  
let $e[i, j]$ is cost of searching a BST
$$
e[i,j] = \sum_{l=i}^{j}(depth_T(k_l)+1)p_l + \sum_{l=i-1}^{j}(depth_T(d_l)+1)q_l \\        
 = p_r + (e[i,r-1] + w(i,r-1)) + (e[r+1,j]+ w(r+1,j)) \\ 
 = e[i,r-1] + e[r+1,j] + w(i,j) \\
 ,where \ w(i,j) = \sum_{l=i}^{j}p_l + \sum_{l=i-1}^{j}q_l
$$

 note that 
 
 r node을 기준으로  {subtree [i .. r-1]} + {r node} + {subtree [r+1 .. j]} 로 나뉜다고 생각하면 
 [i..j] internal nodes를 가진 subtree 의 $depth_i$ 가 1 증가 함으로써 $e[i,j]에 $ 
 $w(i,j) = \sum_{l=i}^{j}p_l + \sum_{l=i-1}^{j}q_l$ 이 추가된다. 


>Objective:

>어떤 Binary Tree에서 각 노드에 접근할 확률이 주어졌을때, 

>key를 searching 하는데 최소의 cost 로 searching하는 Optimal BST structure를 찾고 싶다! 


reculsive fomula : 
$$
e[i,j] = \left \{ 
\begin{matrix}
q_{i-1} & \text{if}~ j = i - 1, \\
\min_{i < r \le j}(e[i,r-1] + e[r+1,j] + w(i,j)) & \text{if}~ i \le j. 
\end{matrix}\right.
$$



- bottom up 

$$
 T(n) = O(n^3) 
$$
 
 in order to solve c[1][n],
 
 we have to fill up $n^2$ entries, where each entry takes O(n) time
 
 because choosing among n previous subproblems

root array를 통해 몇 번째 노드를 기준으로 분리하는것이 searching 하는데 이득이 되는지 알 수 있다 .

In [14]:
# bottom up approach ; three nested loop 
def Optimal_BST(p,q,n):
    e = [[None for j in range(0, n+1)] for i in range(1, n+2+1)]   # 나머지칸을 빈칸으로 두기 위해 i 에 +1 을 하였다. 
    w = [[None for j in range(0, n+1)] for i in range(1, n+2+1)]
    root = [[None for j in range(1, n+1+1)] for i in range(1, n+1+1)]
    
    for i in range(1,n+2):               # base case 
        e[i][i-1] = q[i-1]  
        w[i][i-1] = q[i-1]
    
    for l in range(1,n+1):
        for i in range(1,n-l+2):
            j = i+l-1
            e[i][j] = float('inf')     # 무한 대의 값 
            w[i][j] = w[i][j-1] + p[j] + q[j]
            
            for r in range(i, j+1):                       # cost가 min이 되는 r을 찾는다.
                t  = e[i][r-1] + e[r+1][j] + w[i][j]
                
                if t < e[i][j]:
                    e[i][j] = t
                    root[i][j] = r
    
    return e, root  

In [15]:
p = [  -1,  0.15,  0.10,  0.05,  0.10,  0.20]
q = [0.05,  0.10,  0.05,  0.05,  0.05,  0.10]
e,root = Optimal_BST(p,q,len(p)-1)
root

[[None, None, None, None, None, None],
 [None, 1, 1, 2, 2, 2],
 [None, None, 2, 2, 2, 4],
 [None, None, None, 3, 4, 5],
 [None, None, None, None, 4, 5],
 [None, None, None, None, None, 5]]

In [16]:
e

[[None, None, None, None, None, None],
 [0.05, 0.45000000000000007, 0.9, 1.25, 1.75, 2.75],
 [None, 0.1, 0.4, 0.7, 1.2, 2.0],
 [None, None, 0.05, 0.25, 0.6, 1.2999999999999998],
 [None, None, None, 0.05, 0.30000000000000004, 0.9],
 [None, None, None, None, 0.05, 0.5],
 [None, None, None, None, None, 0.1]]

# Greedy Algorithm 
 
 > greedy choice looks best at the moment. 
 
 > it makes a locally optimal choice in the hope that this choice will lead to global optimal solution.

## Activity Selection Problem 

$S_{ij}$ 의 원소 a_k 는 starting time은 $f_i$ 이후, finishing time은 $s_j$ 이전 인 원소이다. 

n 개의 원소중 

$S_{0,n+1}$ 의 원소 갯수가 최대가 되도록 선택을 하고 싶다! (dummy 원소 $a_0, a_{n+1}$ 두고)

c[i.j] : the # of activities in max-size subset of mutually compatible in S[i,j]

reculsive formula :

$$
c[i,j] = \left \{ 
\begin{matrix}
0 & \text{if}~ S_{ij} \ is \ empty, \\
\max_{a_k ∈ S_{ij}}(c[i,k] + c[k,j] + 1) & \text{if}~ S_{ij} \ is \ non-empty. 
\end{matrix}\right.
$$

if we use DP, $T(n) = O(n^2)$, because entries O(n^2), each entry takes O(n)

redefine for greedy algorithm 

$S_{ij} -> S_k $ = {$a_i ∈ S: s_i \ge f_k $} 

If we use greedy algorithm, DP formula can be transformed. 

$$
c[0,n+1] = c[0,m_1] + c[m_1, n+1] + 1\\ 
= c[m_2, n+1] + 1 + 1\\
= c[m_2, n+1] + 1 + 1 + 1\\
= ... \\
= c[m_m, n+1] + m 
$$

note that  $c[0,m] = 0, c[m_1,m_2] = 0, ... ,c[m_{m-1},c_m] = 0$
, where $m \le n $

entries are decreased by O(n), each entry takes O(1)

Therefore, 
$$
T(n) = O(n), \text{ suppose that prepressing sortng }~ a_k \text{ with finishing time } 
$$

In [17]:
# 1. recursive version 
def Recursive_Greedy(s,f,k,n):
    m = k+1
    
    # Find appropriate m for using optimal sol 
    while m <= n and s[m] < f[k]:
        m = m + 1 
    
    if m <= n:
        A = np.array([m]) 
        return np.append(A, Recursive_Greedy(s,f,m,n))
    else:
        return None

In [18]:
# 2. iterative version 
def Iterative_Greedy(s,f):
    n = s.shape[0] - 2
    A = np.array([1]) # A always has a1 
    k = 1 
    for m in range(2,n+1):
        if s[m] >= f[k]:
            A = np.append(A, m)
            k = m 
    return A 

In [19]:
# n = 11
# s[0],f[0] and s[12],f[12] are dummies
# Assume that inputs are already sorted : f[1] <= f[2] <= f[3] <= ... <= f[11]

import numpy as np 
s = np.array([-1,1,3,0,5,3,5,6,8,8,2,12,float('Inf')]) 
f = np.array([0,4,5,6,7,8,9,10,11,12,13,14,-1]) 
A1 = Recursive_Greedy(s,f,0,s.shape[0]-2)
A2 = Iterative_Greedy(s,f)
print("Output of the recursive version:  ", A1)
print("Output of the iterative version:  ", A2)

Output of the recursive version:   [1 4 8 11 None]
Output of the iterative version:   [ 1  4  8 11]


# Knapsack Problem 

0-1 Knapsack problem is not satisfied with Greedy choice property 

- 0-1 Knapsack Problem through Dynamic programming

nW 시간이 걸린다. c[n,W]만큼 loop를 돌면서 작성을 해야하므로, where each entry takes O(1) time
> ### notation : 
>n ; # item 
>W ; max weight for knapsack  
>$c[i][w]$ ; i 는 item index, w 는 possible weight 

In [20]:
# notation :  n ; # item, W ; max weight for knapsack  
# c[i][w] ; i 는 item index, w 는 possible weight 

# bottom up approach 
def DP_Knapsack(n,W,weight,v):
    
    c = np.ones([n+1,W+1]) * -1 # space for memoization 
    
    for w in range(W+1):
        c[0][w] = 0 
        
    for i in range(1,n+1):
        #print(i)
        for w in range(W+1):
            #print(w)
            #print(c)
            if weight[i] <= w:
                c[i][w] = max(c[i-1][w], v[i] + c[i-1][w-weight[i]])
            else: 
                c[i][w] = c[i-1][w]
   
    return c[n][W]

In [21]:
import numpy as np
w = np.array([-1,1,2,3])
v = np.array([-1,60,100,120])
W = 5 # maximum wieght for knapsack 

# Knapsack Problem through Dynamic programming(bottom up approach)
sol = DP_Knapsack(w.shape[0]-1,W,w,v)
print("solution :  ", sol)

solution :   220.0


 - Fractional Knapsack Problem through Greedy algorithm 
 
 Greedy choice : first of all, an item with higer Unit price per weight must be selected 

sorting 하는데 nlgn 시간이 걸리고, greedy algorithm 하는데 n 시간 걸린다. 

In [22]:
def fractional_knapsack(value, weight, capacity):
    """Return maximum value of items and their fractional amounts.
 
    (max_value, fractions) is returned where max_value is the maximum value of
    items with total weight not more than capacity.
    fractions is a list where fractions[i] is the fraction that should be taken
    of item i, where 0 <= i < total number of items.
 
    value[i] is the value of item i and weight[i] is the weight of item i
    for 0 <= i < n where n is the number of items.
 
    capacity is the maximum weight.
    """
    # index = [0, 1, 2, ..., n - 1] for n items
    index = list(range(len(value)))
    # contains ratios of values to weight
    ratio = [v/w for v, w in zip(value, weight)]
    # index is sorted according to value-to-weight ratio in decreasing order
    index.sort(key=lambda i: ratio[i], reverse=True)
 
    max_value = 0
    fractions = [0]*len(value)
    for i in index:
        if weight[i] <= capacity:
            fractions[i] = 1
            max_value += value[i]
            capacity -= weight[i]
        else:
            fractions[i] = capacity/weight[i]
            max_value += value[i]*capacity/weight[i]
            break
 
    return max_value, fractions

In [24]:
n = int(input('Enter number of items: '))
value = input('Enter the values of the {} item(s) in order: '
              .format(n)).split()
value = [int(v) for v in value]
weight = input('Enter the positive weights of the {} item(s) in order: '
               .format(n)).split()
weight = [int(w) for w in weight]
capacity = int(input('Enter maximum weight: '))
 
max_value, fractions = fractional_knapsack(value, weight, capacity)
print('The maximum value of items that can be carried:', max_value)
print('The fractions in which the items should be taken:', fractions)

# 3 
# 60 100 120 
# 10 20 30
# 50
# result : 240 

Enter number of items: 3
Enter the values of the 3 item(s) in order: 60 100 120
Enter the positive weights of the 3 item(s) in order: 10 20 30
Enter maximum weight: 50
The maximum value of items that can be carried: 240.0
The fractions in which the items should be taken: [1, 1, 0.6666666666666666]


# Constructing Huffman code 

Huffman code 를 만들어라. 우선순위 큐(minimum heap 이용) 

suppose that inputs have to be sorted with freq order 

$$
T(n) = O(nlgn)
$$

lgn : extracted by Q 

n : for loop 

In [25]:
# priority queue(minimum heap + ADT) 필요 

def parent(i):
    return (i - 1) >> 1 # 2로 나눔 


def left(i):
    return (i << 1) + 1  # 2 곱함 ; index 0부터 시작이므로 +1


def right(i):
    return (i << 1) + 2 # 2 곱하고 1더함 ; ndex 0부터 시작이므로 +1


def min_heapify(a, i):
    min_idx = i
    l, r = left(i), right(i)
    if l < len(a) and a[l] < a[min_idx]:
        min_idx = l
    if r < len(a) and a[r] < a[min_idx]:
        min_idx = r
    if min_idx != i:
        a[i], a[min_idx] = a[min_idx], a[i] # swape a[i] with a[min_idx]
        min_heapify(a, min_idx)
    
def build_min_heap(a):
    for i in range(int(len(a)/2),-1,-1):
        min_heapify(a, i)
        
########################  ADT #################################################################################

def heap_minimum(a):
    assert(len(a) > 0)
    return a[0] # min-heap 을 따르므로 index 0 일때 가장 minimum 


def heap_extract_min(a):
    assert(len(a) > 0) #양수인지 검사하는 오류 검사 코드 
    val = a[0]
    a[0] = a[-1] # a 배열의 마지막값을 맨 위로 올림 
    del a[-1] # 바뀐 마지막 배열 제거 
    min_heapify(a, 0) # min_heapify를 call 하여, min-heap property 유지 ; it takes O(lgn) times  
    return val # 아까 저장한 min 값 추출 


def heap_decrease_key(a, i, key):  # a[i] 값을 key로 낮추고 min-heap data structure를 따르도록하는 적절한 위치 찾는다 
    assert(key <= a[i]) # key값이 a[i] 보다 낮은지 검사한다. 
    a[i] = key
    while i > 0 and a[i] < a[parent(i)]:  # O(lgn) 만큼 소요 ; root까지 올라가며 비교해야하므로 
        a[i], a[parent(i)] = a[parent(i)], a[i]
        i = parent(i)


def min_heap_insert(a, key):
    a.append(1e100) # 매우 큰값을 sintinel value로 두고 배열에 끝에 그 값을 추가한다. 
    heap_decrease_key(a, len(a) - 1, key) # 새로 생긴 값이 적당한 위치를 찾아가게 된다 it takes O(lgn)

In [26]:
def Huffman(C):
    n = len(C)
    build_min_heap(C)
    Q = C
    print("debug1 ", Q)
    for i in range(1,n):
        x = heap_extract_min(Q)
        y = heap_extract_min(Q)
        z = x + y 
        min_heap_insert(Q, z)
        print("debug2 ", Q)
    
    print("debug3 ",Q)
    
    return heap_extract_min(Q)

In [28]:
#C  = [5,9,12,13,16,45] # character 의 freq가 key를 의미
C = [45,13,12,16,9,5]   #['a','b','c','d','e','f']
Huffman(C)

#This result can be used for assigning Huffman cordword  

debug1  [5, 9, 12, 16, 13, 45]
debug2  [12, 13, 45, 16, 14]
debug2  [14, 16, 45, 25]
debug2  [25, 45, 30]
debug2  [45, 55]
debug2  [100]
debug3  [100]


100