# Algorithm Summary 

# insertion sort 

O($n^2$)

In [1]:
# decreasing order version 
def insertion_sort(a):
    for j in range(1, len(a)):
        key = a[j]
        i = j - 1
        #그전 순서보다 현재가 크면 swap하며 while문을 돌게 된다. 아니면, remain 
        while i >= 0 and a[i] < key:
        #while i >= 0 and a[i] > key:    
            a[i + 1] = a[i]
            i -= 1
        a[i + 1] = key

In [2]:
# increasing order version 
def insertion_sort(a):
    for j in range(1, len(a)):
        key = a[j]
        i = j - 1
        #그전 순서보다 현재가 크면 swap하며 while문을 돌게 된다. 아니면, remain 
        while i >= 0 and a[i] > key:    
            a[i + 1] = a[i]
            i -= 1
        a[i + 1] = key

In [3]:
A = [(31,'b'),(41,'c'),(59,'f'),(26,'a'),(41,'d'),(58,'e')]
insertion_sort(A)
print(A)

[(26, 'a'), (31, 'b'), (41, 'c'), (41, 'd'), (58, 'e'), (59, 'f')]


# linear search 

it takes O(n) time

In [4]:
# v는 item값, return index값 
def linear_search(a, v):
    for i in range(len(a)):
        if a[i] == v:
            return i
    return None

In [5]:
linear_search(A, (58,'e'))

4

# merge sort

time complexity analysis through recursion tree 

T(n) = 2T(n/2) + n 

     = ...
     
     = 2^k T(n/2^k) + kn 
     
     = O(nlgn)    because n/2^k = 1 < = > k = lgn 

In [6]:
# A[p..r] 까지 A[p..q] , A[q+1..r] 로 divide 를 통해 sorting을 한다.  
# increasing order merge 
def merge(A,p,q,r):  # O(n) time
    n1 = q - p + 1 
    n2 = r - q 
    # let L[0..n1] and R[0.. n2] be new arrays
    L = [] 
    R = []
    for i in range(n1):    # L[0.. n1-1] <- A[p..q] 
        L.append(A[p + i])  
    for j in range(n2):
        R.append(A[q + j + 1])  # R[0.. n2-1] <- A[q+1..r]
    L.append(float('inf'))
    R.append(float('inf')) 
    i = 0 
    j = 0
    # merge L[i] and R[j] in order to sort A[p.. q]
    for k in range(p,r+1):
        if L[i] <= R[j]:
            A[k] = L[i]
            i += 1
        else: 
            A[k] = R[j]
            j += 1 

In [7]:
# A[p..r] 까지 A[p..q] , A[q+1..r] 로 divide 를 통해 sorting을 한다.  
# decreasing order merge 
def merge(A,p,q,r):  # O(n) time
    n1 = q - p + 1 
    n2 = r - q 
    # let L[0..n1] and R[0.. n2] be new arrays
    L = [] 
    R = []
    for i in range(n1):    # L[0.. n1-1] <- A[p..q] 
        L.append(A[p + i])  
    for j in range(n2):
        R.append(A[q + j + 1])  # R[0.. n2-1] <- A[q+1..r]
    L.append(-float('inf'))
    R.append(-float('inf')) 
    i = 0 
    j = 0
    # merge L[i] and R[j] in order to sort A[p.. q]
    for k in range(p,r+1):
        if L[i] >= R[j]:
            A[k] = L[i]
            i += 1
        else: 
            A[k] = R[j]
            j += 1 

In [8]:
# devide, conquer, combine을 통해 recursive하게 sorting을 한다. 
def merge_sort(A,p,r):  # A[p..r]까지 sorting 
    if p < r:
        q = (p + r)// 2     # devide A[p .. q], A[q+1 .. r] in order to make size as similiar as possible 
        merge_sort(A,p,q)
        merge_sort(A,q+1,r)
        merge(A,p,q,r)
# total running time : O(nlgn)
    

In [9]:
A = [3,41,52,26,38,57,9,49,8,2,4,5,1,2,3] 
# tuple 은 사용할 수 없다. 왜냐하면 A[0] = (31,'b') 이런 식이기 때문에 
#A = [(31,'b'),(41,'c'),(59,'f'),(26,'a'),(41,'d'),(58,'e')] 
merge_sort(A,0,14)
A

[57, 52, 49, 41, 38, 26, 9, 8, 5, 4, 3, 3, 2, 2, 1]

# binary search 

 assume that A is already sorted 
 
 T(n) = T(n/2) + 1 
      = O(lgn)

In [10]:
# assume that A is sorted by increasing order 
def binary_search(A,low,high,X):
    if low == high:
        if A[low] == X:
            return low
        else:
            return print("Not found")
    else: 
        mid = (low + high)// 2 
        print(mid,A[mid],X)
        if A[mid] > X:
            return binary_search(A,low,mid-1,X)
        else:
            return binary_search(A,mid+1,high,X)


In [11]:
# assume that A is sorted by decreasing order 
def binary_search(A,low,high,X):
    if low == high:
        if A[low] == X:
            return low
        else:
            return print("Not found")
    else: 
        mid = (low + high)// 2 
        print(mid,A[mid],X)
        if A[mid] < X:
            return binary_search(A,low,mid-1,X)
        else:
            return binary_search(A,mid+1,high,X)

In [12]:
print(A)
binary_search(A,0,14,9)

[57, 52, 49, 41, 38, 26, 9, 8, 5, 4, 3, 3, 2, 2, 1]
7 8 9
3 41 9
5 26 9


6

# heap sort 

running time : O($nlgn$)

because heapify running time : O(lgn)  <=  T(n) <= T(2n/3) + Θ(1) // 2n/3 input recursive + swapping(Θ(1))

In [13]:
class heap:
    
    def __init__(self,a):
        self.heap_size = len(a) - 1 # index 는 0 ~ len(a) - 1 이므로 
        
        # mutable variable : self.h가 heap class의 function에 의해 바뀌면 a도 바뀐다. 
        self.h = a  
    
    # Binary shifting 으로 생각  python 에서는 index 0 부터 사용 하므로 
    def parent(self,i):
        if i <= self.heap_size:
            return (i - 1) >> 1 
        else: return i # heapify 연산에서 if 문에서 비교 연산에 대해 결과가 Flase가 나와야하고, 마지막에 i로 largest(smalliest) 결정


    def left(self, i):
        if (((i << 1) + 1) <= self.heap_size):
            return (i << 1) + 1  # 2 곱함 ; index 0부터 시작이므로 +1
        else: return i 

    def right(self, i):
        if (((i<<1) + 2) <= self.heap_size):
            return (i << 1) + 2 # 2 곱하고 1더함 ; ndex 0부터 시작이므로 +1
        else: return i 

    
    # T(n) <= T(2n/3) + Θ(1)
    def min_heapify(self, i):
     
        # smallest = argmin{a[i] , a[l], a[r]} 
        l, r = self.left(i), self.right(i) 
        if (l <= len(self.h)) and (self.h[l] < self.h[i]):
            smallest = l
        else: smallest = i 
        if (r <= len(self.h)) and (self.h[r] < self.h[smallest]):
            smallest = r
    
        # i 가 smallest 가 아니라면 a[smallest] 와 swap     
        if smallest != i:
            self.h[i], self.h[smallest] = self.h[smallest], self.h[i] # swape a[i] with a[min_idx]
            self.min_heapify(smallest)             # recursive call 
    
        # worst case running time : O(lgn)   
        
    def max_heapify(self, i):

        # largest = argmax{a[i] , a[l], a[r]} 
        l, r = self.left(i), self.right(i) 
        if (l <= len(self.h)) and (self.h[l] > self.h[i]):
            largest = l
        else: largest = i 
        if (r <= len(self.h)) and (self.h[r] > self.h[largest]):
            largest = r
        
        #print(largest, i ,"// largest, i : debug2")
        # i 가 largest가 아니라면 a[largest] 와 swap 
        # i = largest이면, recursive call 하지 않는다. 위치 그대로 (same key가 있다면 그대로 위치 )
        if largest != i:
            self.h[i], self.h[largest] = self.h[largest], self.h[i] # swape a[i] with a[max_idx]
            self.max_heapify(largest)             # recursive call 
        # worst case running time : O(lgn)
    
    # internal nodes 만 heapify call하면 heap property 모두 만족되게 된다..
    def build_min_heap(self):
        self.heap_size = len(self.h) - 1
        for i in range((len(self.h)-1)//2,-1,-1):
            self.min_heapify(i)
            
        #running time : O(nlgn ) -> tighter upper bound : O(n)
        
    def build_max_heap(self):
        self.heap_size = len(self.h) - 1
        for i in range((len(self.h)-1)//2,-1,-1):
            self.max_heapify(i)
            
        # running time : O(nlgn) 인데 tighter한 upper bound is O(n)
            
    def size(self):
        return (self.heap_size + 1)
            
    """ heap sort implementation using heap"""
    def heapsort_do(self):      # decreasing order
        # preprocessing
        T = self.h.copy()   # sorting 하면 heap property 특성이 깨지기 때문에 
        temph = heap(T)
        
        # using min heap 
        temph.build_min_heap()                     # min heap 을 만들고, 
        for i in range(len(temph.h)-1, -1, -1):          # for loop 에서 heap property를 유지시키며, decreasing order로 sorting 
            temph.h[0], temph.h[i] = temph.h[i], temph.h[0]                # 그 과정에서 heap에 들어간 array는 점점 줄어든다. 
            temph.heap_size = temph.heap_size - 1    # [[ heap영역      ]  sorting된 data]  : total data
            temph.min_heapify(0)                  # [[null]   sorting completed       ]
        # running time : O(nlgn)
        return T
    
    def heapsort_io(self):      # decreasing order
        # preprocessing
        T = self.h.copy()   # sorting 하면 heap property 특성이 깨지기 때문에 
        temph = heap(T)
        
        # using min heap 
        temph.build_max_heap()                     # min heap 을 만들고, 
        for i in range(len(temph.h)-1, -1, -1):          # for loop 에서 heap property를 유지시키며, decreasing order로 sorting 
            temph.h[0], temph.h[i] = temph.h[i], temph.h[0]                # 그 과정에서 heap에 들어간 array는 점점 줄어든다. 
            temph.heap_size = temph.heap_size - 1    # [[ heap영역      ]  sorting된 data]  : total data
            temph.max_heapify(0)                  # [[null]   sorting completed       ]
        # running time : O(nlgn)
        return T
    

""" heap property를 만족시키는 것을 유지 하도록 해야한다. """    
class priority_queue_min(heap):
    
    def __init__(self, a):
        self.heap_size = len(a) - 1 # index 는 0 ~ len(a) - 1 이므로 
        
        # self.h have to always maintain min-heap property
        # self.h is a mutable type 
        self.h = a
        self.build_min_heap()  
    
    
    # ※ self.h 는 min heap property를 만족하는 array여야 한다.
    def heap_minimum(self):
        return self.h[0]
    
    def heap_extract_min(self):
        if self.heap_size < 0:
            print("heap underflow: empty array")
            return None
        mn = self.h[0] # heap 에 root 에 있는 min 값 
        
        # mn 값을 빼왔으니, 제일 뒤에있는 index에 있는 element를 빼와서 haep property를 만족하도록 한다.
        self.h[0] = self.h[len(self.h) - 1]
        self.heap_size = self.heap_size - 1
        self.min_heapify(0)
        
        del self.h[self.heap_size + 1]

        #runnig time: O(lgn)
        return mn 
         
    
    
    """ prim Algorithm을 위해 정의(Dijkstra algorithm에서도 쓰임) 
        key_update는 decrease_key function과 동일하게 동작한다. 
        decrease key는 O(lgn)시간이 걸리도록 할 수 있지만, 
        tuple의 값에 대해서 구현하기 어려워서 brutal force 방식으로 만듦 
    """
    # heap property를 만족시키면서 self.h[idex]의 (key, value) = item 을 바꿈  
    def key_update(self, idex, newitem):
        if idex == None:
            return 
        self.h[idex] = newitem
        self.build_min_heap()   
        
    def find_index(self, value):
        for k in range(self.size()):
            if self.h[k][1] == value:
                return k 
            
    def heap_included(self, v):
        for k in range(self.size()):
            if self.h[k][1] == v:
                return True 
            
""" heap property를 만족시키는 것을 유지 하도록 해야한다. """    
class priority_queue_max(heap):
    
    def __init__(self, a):
        self.heap_size = len(a) - 1 # index 는 0 ~ len(a) - 1 이므로 
        
        # self.h have to always maintain min-heap property
        # self.h is a mutable type 
        self.h = a
        self.build_max_heap()  
    
    
    # ※ self.h 는 min heap property를 만족하는 array여야 한다.
    def heap_maximum(self):
        return self.h[0]
    
    def heap_extract_max(self):
        if self.heap_size < 0:
            print("heap underflow: empty array")
            return None
        mx = self.h[0] # heap 에 root 에 있는 min 값 
        
        # mx 값을 빼왔으니, 제일 뒤에있는 index에 있는 element를 빼와서 haep property를 만족하도록 한다.
        self.h[0] = self.h[len(self.h) - 1]
        self.heap_size = self.heap_size - 1
        self.max_heapify(0)
        
        del self.h[self.heap_size + 1]

        #runnig time: O(lgn)  //  because max_heapify fucntion requires O(lgn)
        return mx 
         
    """tuple 에 대해서는 동작 안함 """
    # index i 의 key를 증가시켜도 여전히 children은 heap property 를 만족한다.
    # 하지만, parent는 property를 만족시키는것을 유지하도록 해야한다. 
    def heap_increase_key(self, i, key):
        if key < self.h[i]:
            print("error: new key is smaller than current key ")
        self.h[i] = key 
        # parent를 property를 만족시키는것을 유지하도록함
        # 증가시킨 key값 a[i] 보다 parent의 key가 작다면, property를 유지하도록 바꿔야함(root 까지)
        while i>0 and self.h[self.parent(i)] < self.h[i]: 
            self.h[i], self.h[self.parent(i)] = self.h[self.parent(i)], self.h[i] 
            i = self.parent(i)
        # running time O(lgn)
    
    def max_heap_insert(self, key):
        self.heap_size = self.heap_size + 1
        self.h.append(-1*float('inf')) # 최소값으로 지정 (heap property 위배 안 되야 하므로)
        self.heap_increase_key(self.heap_size, key)
        # running time O(lgn)
    
    
    
    """ prim Algorithm을 위해 정의(Dijkstra algorithm에서도 쓰임) 
        key_update는 decrease_key function과 동일하게 동작한다. 
        decrease key는 O(lgn)시간이 걸리도록 할 수 있지만, 
        tuple의 값에 대해서 구현하기 어려워서 brutal force 방식으로 만듦 
    """
    # heap property를 만족시키면서 self.h[idex]의 (key, value) = item 을 바꿈  
    def key_update_min(self, idex, newitem):
        if idex == None:
            return 
        self.h[idex] = newitem
        self.build_min_heap()   
    def key_update_max(self, idex, newitem):
        if idex == None:
            return 
        self.h[idex] = newitem
        self.build_max_heap()   
        
    def find_index(self, value):
        for k in range(self.size()):
            if self.h[k][1] == value:
                return k 
            
    def heap_included(self, v):
        for k in range(self.size()):
            if self.h[k][1] == v:
                return True 

In [14]:
A = [(21,'a'), (65,'b'), (68,'c'), (31,'d'), (13,'e'), (24,'f'), (19,'g'), (14,'h'), (32,'i'), (26,'j')]
h = heap(A)
print(h.heapsort_do())  
print(h.heapsort_io())
print(A)

[(68, 'c'), (65, 'b'), (32, 'i'), (31, 'd'), (26, 'j'), (24, 'f'), (21, 'a'), (19, 'g'), (14, 'h'), (13, 'e')]
[(13, 'e'), (14, 'h'), (19, 'g'), (21, 'a'), (24, 'f'), (26, 'j'), (31, 'd'), (32, 'i'), (65, 'b'), (68, 'c')]
[(21, 'a'), (65, 'b'), (68, 'c'), (31, 'd'), (13, 'e'), (24, 'f'), (19, 'g'), (14, 'h'), (32, 'i'), (26, 'j')]


In [15]:
pq_min = priority_queue_min(A)

print(pq_min.h)
pq_min.heap_extract_min()
print(A)

[(13, 'e'), (14, 'h'), (19, 'g'), (21, 'a'), (26, 'j'), (24, 'f'), (68, 'c'), (31, 'd'), (32, 'i'), (65, 'b')]
[(14, 'h'), (21, 'a'), (19, 'g'), (31, 'd'), (26, 'j'), (24, 'f'), (68, 'c'), (65, 'b'), (32, 'i')]


In [16]:
pq_max = priority_queue_max(A)
print(pq_max.h)
pq_max.heap_extract_max()
print(A)

[(68, 'c'), (65, 'b'), (24, 'f'), (32, 'i'), (26, 'j'), (14, 'h'), (19, 'g'), (31, 'd'), (21, 'a')]
[(65, 'b'), (32, 'i'), (24, 'f'), (31, 'd'), (26, 'j'), (14, 'h'), (19, 'g'), (21, 'a')]


In [17]:
A = [(21,'a'), (65,'b'), (68,'c'), (31,'d'), (13,'e'), (24,'f'), (19,'g'), (14,'h'), (32,'i'), (26,'j')]
pq_max = priority_queue_max(A)
print(A)
pq_max.key_update_max(pq_max.find_index('d'), (84,'d'))
print(A)

[(68, 'c'), (65, 'b'), (24, 'f'), (32, 'i'), (26, 'j'), (21, 'a'), (19, 'g'), (14, 'h'), (31, 'd'), (13, 'e')]
[(84, 'd'), (68, 'c'), (24, 'f'), (65, 'b'), (26, 'j'), (21, 'a'), (19, 'g'), (14, 'h'), (32, 'i'), (13, 'e')]


In [18]:
 """tuple 에 대해서는 동작 안함 """
A = [21, 65, 68, 31, 13, 24, 19, 14, 32, 26]
#A = [(21,'a'), (65,'b'), (68,'c'), (31,'d'), (13,'e'), (24,'f'), (19,'g'), (14,'h'), (32,'i'), (26,'j')]

pq_max = priority_queue_max(A)
print(A)
pq_max.heap_increase_key(5,30)
print(A)

pq_max.max_heap_insert(35)
print(A)
print(pq_max.h)
print(pq_max.heap_size)
#print(pq_max.size())

[68, 65, 24, 32, 26, 21, 19, 14, 31, 13]
[68, 65, 30, 32, 26, 24, 19, 14, 31, 13]
[68, 65, 30, 32, 35, 24, 19, 14, 31, 13, 26]
[68, 65, 30, 32, 35, 24, 19, 14, 31, 13, 26]
10


# Quick sort 

divide and conquer and combine approach 

time complexity analysis : partition procedure 가 어떤 index를 내놓느냐에 따라 다르다.

 𝑇(𝑛)=max_(0≤𝑞≤𝑛−1) (𝑇(𝑞)+𝑇(𝑛−𝑞−1))+"Ɵ(n) "

    - worst case : T(n) = O(n^2)  , because n-1, 1 로 나뉨
    
    - best case  : T(n) = O(nlgn) , because always n/2, n/2 로 나뉨
    
    
using randomized quick sort : running time = O(nlgn)

In [19]:
# increasing order 
def partition(a, p, r):
    x = a[r]
    i = p - 1
    
    # for 문에서 linear searching을 하며, a[p..r-1] 을 p[r]과 비교하여 작으면 왼쪽, 크면 오른쪽으로 partitioning : O(n)
    for j in range(p, r):
        if a[j] <= x: # inequality 반대로 reverse 
            i += 1
            a[i], a[j] = a[j], a[i]
        
    i += 1
    a[i], a[r] = a[r], a[i]
    return i

In [20]:
# decreasing order 
def partition(a, p, r):
    x = a[r]
    i = p - 1
    
    # for 문에서 linear searching을 하며, a[p..r-1] 을 p[r]과 비교하여 작으면 왼쪽, 크면 오른쪽으로 partitioning : O(n)
    for j in range(p, r):
        if a[j] >= x: # inequality 반대로 reverse 
            i += 1
            a[i], a[j] = a[j], a[i]
        
    i += 1
    a[i], a[r] = a[r], a[i]
    return i

In [21]:
def quicksort(a, p, r):
    if p < r :   # p >= r 이 되면 종료 
        q = partition(a, p, r)
        quicksort(a, p, q -1)              
        quicksort(a, q + 1, r)

In [22]:
import random

def randomized_partition(a, p, r):
    i = random.randint(p, r)
    a[r], a[i] = a[i], a[r]
    return partition(a, p, r)


def randomized_quicksort(a, p, r):
    if p < r:
        q = randomized_partition(a, p, r)
        randomized_quicksort(a, p, q-1)
        randomized_quicksort(a, q+1, r)

In [23]:
A = [(21,'a'), (65,'b'), (68,'c'), (31,'d'), (13,'e'), (24,'f'), (19,'g'), (14,'h'), (32,'i'), (26,'j')]
quicksort(A,0,9)
print(A) 

[(68, 'c'), (65, 'b'), (32, 'i'), (31, 'd'), (26, 'j'), (24, 'f'), (21, 'a'), (19, 'g'), (14, 'h'), (13, 'e')]


In [24]:
A = [(21,'a'), (65,'b'), (68,'c'), (31,'d'), (13,'e'), (24,'f'), (19,'g'), (14,'h'), (32,'i'), (26,'j')]
randomized_quicksort(A,0,9)
print(A)

[(68, 'c'), (65, 'b'), (32, 'i'), (31, 'd'), (26, 'j'), (24, 'f'), (21, 'a'), (19, 'g'), (14, 'h'), (13, 'e')]


# counting sort 

 Linear time algorithm using many memories 
 
 ※ inputs(A[]: keys) have to be non-negative inputs <= k 
     , C[0.. k] memeories are used 
 
    A는 양수여야 한다. 
    마지막 for loop가 stable이어야 radix sort에서 쓸 수 있다
    (stable : input에서 먼저 나타난 것이 output에서도 먼저 나타난다.). 
    O(n + k)

In [25]:
def counting_sort(A,B,k):
    C = [None] * (k+1) 
    for i in range(k+1):
        C[i] = 0
    
    for j in range(len(A)):
        C[A[j]] = C[A[j]] + 1
    for i in range(1,k+1):
        C[i] = C[i] + C[i-1]
        
    # 이 for loop부분이 내림 차순이어야 stable algorithm이 된다.     
    for j in range(len(A)-1, -1,-1):
        B[C[A[j]]-1] = A[j]
        C[A[j]] = C[A[j]] - 1
        #print(A)
        #print(B,j)
        #print(C)
        

In [26]:
import numpy as np
#A = [21, 65, 68, 31, 13, 24, 19, 14, 32, 26]
# tuple에서 사용 할 수 없다.
#A = [(21,'a'), (65,'b'), (68,'c'), (31,'d'), (13,'e'), (24,'f'), (19,'g'), (14,'h'), (32,'i'), (26,'j')]
A = [1,4,100,3,1,0,3,0]
B = [None]*len(A)
k = A[np.argmax(A)]
#k = 68

counting_sort(A,B,k)
B

[0, 0, 1, 1, 3, 3, 4, 100]

# radix sort 

 ### ※ stable한 subroutine을 사용해야 한다. 
 ### LSD 부터 MSD순으로 sorting한다.
 ### non negative 값을 가져야한다.
 n개의 d digit에 대해 각 element는 k 이하여야한다. 
 
 runnning time: O(d(n+k))
 
 e.g for n d(= 4) digit inputs(xxx.xxx.xxx.xxx ip address),   
                                   
     each digit takes on 0 ~ 255 value k = 2^8 (8 bit, r =8), that is, d = b/r = 2^8/8 = 4  

In [27]:
import numpy as np
# A 는 d × n numpy array input: n d digit 

# A의 각 자리수를 이용하여 정렬 하는 것이므로 행을 변경 하면 안된다.
def radix_sort_error(A,d):
    B = -np.ones([len(A), len(A[0])])
    #print(B)
    for i in range(d-1,-1,-1):
        k = A[np.argmax(A[:, i])][i]
        #print(k)
        counting_sort(A[:, i],B[:, i],k)
        print(B, "Debug###")
        
        
# counting sort가 stable 함을 이용하여 각 자리수를 이용한 sorting을 한다.
def counting_sort_with_digit(A,B,k,d):
    C = [None] * (k+1)  
    for i in range(k+1):
        C[i] = 0
    
    for j in range(len(A)):
        C[int(A[:, d][j])] = C[int(A[:, d][j])] + 1
    for i in range(1,k+1):
        C[i] = C[i] + C[i-1]
        
    # 이 for loop부분이 내림 차순이어야 stable algorithm이 된다.     
    for j in range(len(A)-1, -1,-1):
        B[int(C[int(A[:, d][j])]-1)] = A[j]
        C[int(A[:, d][j])] = C[int(A[:, d][j])] - 1

        
# A 는 d × n numpy array input: n d digit 
def radix_sort(A,d):
    
    for i in range(d-1,-1,-1):
        B = -np.ones([len(A), len(A[0])])
        k = int(A[np.argmax(A[:, i])][i])
        counting_sort_with_digit(A,B,k,i)
        A = B                               # output 이 새로운 input이 되어야함
        print(B, "Debug###")
        

In [28]:
import numpy as np
# n = 4, d = 3 inputs 
#A = np.array([[2,4,6],[9,2,5],[2,3,8],[9,2,3]])
A = np.array([[244,86,195,200],[198,200,178,3],[192,180,158,25],[100,86,20,9]])

radix_sort_error(A,len(A[0]))
print(" >> error 정정")
radix_sort(A,len(A[0]))

[[ -1.  -1.  -1.   3.]
 [ -1.  -1.  -1.   9.]
 [ -1.  -1.  -1.  25.]
 [ -1.  -1.  -1. 200.]] Debug###
[[ -1.  -1.  20.   3.]
 [ -1.  -1. 158.   9.]
 [ -1.  -1. 178.  25.]
 [ -1.  -1. 195. 200.]] Debug###
[[ -1.  86.  20.   3.]
 [ -1.  86. 158.   9.]
 [ -1. 180. 178.  25.]
 [ -1. 200. 195. 200.]] Debug###
[[100.  86.  20.   3.]
 [192.  86. 158.   9.]
 [198. 180. 178.  25.]
 [244. 200. 195. 200.]] Debug###
 >> error 정정
[[198. 200. 178.   3.]
 [100.  86.  20.   9.]
 [192. 180. 158.  25.]
 [244.  86. 195. 200.]] Debug###
[[100.  86.  20.   9.]
 [192. 180. 158.  25.]
 [198. 200. 178.   3.]
 [244.  86. 195. 200.]] Debug###
[[100.  86.  20.   9.]
 [244.  86. 195. 200.]
 [192. 180. 158.  25.]
 [198. 200. 178.   3.]] Debug###
[[100.  86.  20.   9.]
 [192. 180. 158.  25.]
 [198. 200. 178.   3.]
 [244.  86. 195. 200.]] Debug###


# bucket sort 

assume that inputs ∋ [0,1) and inputs are generated by random process 

average running time: O(n)

버켓에 list형식으로 담아 정렬한다. 

In [29]:
import math
import numpy as np

def bucket_sort(A):
    n = len(A)
    B = [None] * n
    C = []
    
    # O(n) 
    for i in range(n):
        B[i] = list([])
    for i in range(n):
        B[math.floor(n*A[i])].append(A[i])  
        
    #     
    for i in range(n):
        B[i].sort()
    
    # concatenate the lists B[0..n-1] togeter in order 
    for i in range(n):
        if B[i] != []:
            for j in range(len(B[i])):
                C.append(B[i][j])
    return C

In [ ]:
import random
A = [None] * 10
for i in range(len(A)):
    A[i] = random.random()
print(A)
print("#### sorting후")    
bucket_sort(A)



# i th order statistic 

# using array(insertion sort)

index >= 1

In [84]:
# increasing order version 
def insertion_sort(a):
    for j in range(1, len(a)):
        key = a[j]
        i = j - 1
        #그전 순서보다 현재가 크면 swap하며 while문을 돌게 된다. 아니면, remain 
        while i >= 0 and a[i] > key:    
            a[i + 1] = a[i]
            i -= 1
        a[i + 1] = key

In [148]:
# increasing order version   : ith smallest order element
def find_ith_order_with_insertion_sort(A,index):
    R = [None]*index
    i = 0
    
    for j in range(len(A)):
    
        if j <= index - 1:
            R[j] = A[j]
            key = R[j]
            i = j - 1
        else:
            if R[index - 1] >= A[j]:
                R[index - 1] = A[j]
            key = R[index - 1]
            i = index - 2 
            
        while i>=0 and R[i] > key:
            R[i+1] = R[i]
            i -= 1
            R[i + 1] = key 
        #print(R)
    return R[index-1]

In [151]:
A  = [3,2,1,6,13,5,12,15,11,10,4,9]

print(find_ith_order_with_insertion_sort(A,5))
insertion_sort(A)
A

5


[1, 2, 3, 4, 5, 6, 9, 10, 11, 12, 13, 15]

# using heap 

In [188]:
# Find ith smallest order element
def find_ith_order_with_heap(A,index):
    h = heap(A[0:index]) 
    h.build_max_heap()
    
    for j in range(index,len(A)):
        if h.h[0] > A[j]:
            h.h[0] = A[j]
            #print(A[j], "insert !! and heapify ")
            h.max_heapify(0)
            #print(h.h, "result")
        #print(h.h)
    return h.h[0]

In [196]:
#A = [3,2,1,6,13,5,12,15,11,10,4,9]
A = [(31,'b'),(41,'c'),(59,'f'),(26,'a'),(41,'d'),(58,'e')]
find_ith_order_with_heap(A,3)

(41, 'c')

# using quick sort 

using devide and conquer technique

index >=1

randomized partition을 쓰면 E[T(n)] = O(n)

In [205]:
# increasing order 
def partition(a, p, r):
    x = a[r]
    i = p - 1
    
    # for 문에서 linear searching을 하며, a[p..r-1] 을 p[r]과 비교하여 작으면 왼쪽, 크면 오른쪽으로 partitioning : O(n)
    for j in range(p, r):
        if a[j] <= x: # inequality 반대로 reverse 
            i += 1
            a[i], a[j] = a[j], a[i]
        
    i += 1
    a[i], a[r] = a[r], a[i]
    return i

def randomized_partition(a, p, r):
    i = random.randint(p, r)
    a[r], a[i] = a[i], a[r]
    return partition(a, p, r)

def quicksort(a, p, r):
    if p < r :   # p >= r 이 되면 종료 
        q = partition(a, p, r)
        quicksort(a, p, q -1)              
        quicksort(a, q + 1, r)

In [206]:
def find_ith_order_with_qick(A,p,r,i):
    if p == r:
        return A[p]
    q = partition(A,p,r)
    k = q - p + 1       # [1 ..p p+1 ..r] 에서 k는 p .. r 까지의 갯수 
    
    if i == k: 
        return A[q]
    
    elif i < k:
        return find_ith_order_with_qick(A,p,q-1,i)
    else:
        return find_ith_order_with_qick(A,q+1,r,i-k)
        
def find_ith_order_with_randomqick(A,p,r,i):
    if p == r:
        return A[p]
    q = randomized_partition(A,p,r)
    k = q - p + 1       # [1 ..p p+1 ..r] 에서 k는 p .. r 까지의 갯수 
    
    if i == k: 
        return A[q]
    
    elif i < k:
        return find_ith_order_with_qick(A,p,q-1,i)
    else:
        return find_ith_order_with_qick(A,q+1,r,i-k)
        

In [210]:
A = [3,2,1,6,13,5,12,15,11,10,4,9]
print(find_ith_order_with_qick(A,0,11,8))
print(find_ith_order_with_randomqick(A,0,11,8))

10
10
