# Finding all pair shortest path 

graph's node has a number 

    self.nodes[G.nm[v].number].number 

graph class has W matrix make function 

def Myweight():
    if self.nm[u].edge[v] is not None: # from u to v weight
        W[self.nm[u].number][self.nm[v].number] = self.nm[u].edge[v]
        

In [4]:
import WeightGraph
%run WeightGraph.py

In [6]:
g = {'a': set(['b','c','e']),
     'b': set(['d','e']),
     'c': set(['b']),
     'd': set(['a','c']),
     'e': set(['d'])}

w = {'a': {'b':3, 'c':8, 'e':-4},
     'b': {'d':1, 'e':7},
     'c': {'b':4},
     'd': {'a':2, 'c':-5},
     'e': {'d':6}}


G = Graph(g,w)

In [8]:
import numpy as np 
from time import *  

""" compute L' <= L using W  // running time : O(n^3)"""
def extend_shortest_paths(L,W):
    n = len(L)
    nL = np.ones((n,n))
    
    for i in range(n):
        for j in range(n):
            nL[i][j] = float('inf')
            for k in range(n):
                nL[i][j] = min(nL[i][j], L[i][k] + W[k][j])
    return nL

""" compute L(n-1) // running time : O(n^4) bottom up approach(DP) """
def show_all_pairs_shortest_paths(W):
    start_time = time()
    n = len(W)
    L1 = W
    Lpm = L1                                  #Lpm = Lm-1 meanning  
    for m in range(2,n):
        Lm = np.ones((n,n))
        Lm = extend_shortest_paths(Lpm,W)
        Lpm = Lm
    print("---it takes %s seconds ---" % (time() - start_time))
    return Lm 

""" L(n-1 ) 이 shortest path weight 이므로, 그 이후 아무리 계산해도, 변하지 않음을 이용하여 
    running time 개선 : O(n^3 × lgn)"""
def faster_all_pairs_shortest_paths(W):
    start_time = time()
    n = len(W)
    L1 = W
    Lm = L1
    m = 1
    while m < n - 1:                                      # this loop takes O(lgn * n^3)
        L2m = np.ones((n,n))
        L2m = extend_shortest_paths(Lm,Lm)                # O(n^3)
        Lm = L2m
        m = m*2
    print("---it takes %s seconds ---" % (time() - start_time))
    return Lm 

In [10]:
W = G.myweight()
print(W)

(node.number :  0 , node.name :  a  )
(node.number :  1 , node.name :  b  )
(node.number :  2 , node.name :  c  )
(node.number :  3 , node.name :  d  )
(node.number :  4 , node.name :  e  )
[[ 0.  3.  8. inf -4.]
 [inf  0. inf  1.  7.]
 [inf  4.  0. inf inf]
 [ 2. inf -5.  0. inf]
 [inf inf inf  6.  0.]]


In [11]:
result1 = extend_shortest_paths(W,W)
result1

array([[ 0.,  3.,  8.,  2., -4.],
       [ 3.,  0., -4.,  1.,  7.],
       [inf,  4.,  0.,  5., 11.],
       [ 2., -1., -5.,  0., -2.],
       [ 8., inf,  1.,  6.,  0.]])

In [13]:
result2 = show_all_pairs_shortest_paths(W)
result2

---it takes 0.0014624595642089844 seconds ---


array([[ 0.,  1., -3.,  2., -4.],
       [ 3.,  0., -4.,  1., -1.],
       [ 7.,  4.,  0.,  5.,  3.],
       [ 2., -1., -5.,  0., -2.],
       [ 8.,  5.,  1.,  6.,  0.]])

In [14]:
result3 = faster_all_pairs_shortest_paths(W)
result3

---it takes 0.0009698867797851562 seconds ---


array([[ 0.,  1., -3.,  2., -4.],
       [ 3.,  0., -4.,  1., -1.],
       [ 7.,  4.,  0.,  5.,  3.],
       [ 2., -1., -5.,  0., -2.],
       [ 8.,  5.,  1.,  6.,  0.]])