#  Floyd Warshall Algorithm 

가정상황: negative weight cycle이 없다. 
Dynamic programming을 어떻게 하느냐에 따라 효율적인 알고리즘을 만들 수 있다. 
d(k)[i,j] 는 #k vertex를 intermidate vertex로 하여 src vertex i 로부터 vertex j 까지 가는 shortest path 의 weight이다 . 

running time : O(n^3)

In [3]:
import WeightGraph
%run WeightGraph.py

In [4]:
import numpy as np
from time import * 

""" running time : tree nested loop 이므로 O(n^3) : entry를 n*n*n 에 대해 채워넣어야한다."""
def floyd_warshall(W):
    start_time = time()
    n = len(W)
    D = np.ones((n,n,n))
    D[0] = W
    Dnk = D[0]
    Df = np.ones((n,n))
    
    # procedure 는 k = 1 부터 n 이고 python은 index 0~n-1 이기 때문에 약간 복잡하다. 
    for k in range(n):
        D[k] = Dnk # Next iteration 먼저 계산 
        for i in range(n):
            for j in range(n):
                Dnk[i][j] = min(D[k][i][j], D[k][i][k] + D[k][k][j])  
                Df[i][j] = Dnk[i][j]
    D[0] = W
    print("D array :  \n", D) 
    print("---it takes %s seconds ---" % (time() - start_time))
    return Df # final shrotest path info, when k == n 

def floyd_warshall_with_P(G):
    W= G.myweight()
    P0 = G.myinitialpi() 
    
    n = len(W)
    D = np.ones((n,n,n))
    P = np.ones((n,n,n))
    D[0] = W
    P[0] = P0
    Dnk = D[0]
    Pnk = P[0]
    Df = np.ones((n,n))
    Pf = np.ones((n,n))
    
    # procedure 는 k = 1 부터 n 이고 python은 index 0~n-1 이기 때문에 약간 복잡하다. 
    for k in range(n):
        D[k] = Dnk # Next iteration 먼저 계산
        P[k] = Pnk
        for i in range(n):
            for j in range(n):
                if D[k][i][j] <= (D[k][i][k] + D[k][k][j]): 
                    Dnk[i][j] = D[k][i][j]
                    Pnk[i][j] = P[k][i][j]
                    
                    Df[i][j] = Dnk[i][j]
                    Pf[i][j] = Pnk[i][j]
                else: 
                    Dnk[i][j] = D[k][i][k] + D[k][k][j]
                    Pnk[i][j] = P[k][k][j]     

                    Df[i][j] = Dnk[i][j]
                    Pf[i][j] = Pnk[i][j]
    
    D[0] = W
    P[0] = P0
    print("D array :  \n", D) 
    print("P array :  \n", P)
    return Df, Pf # final shrotest path info, when k == n 

In [2]:
g = {'a': set(['b','c','e']),
     'b': set(['d','e']),
     'c': set(['b']),
     'd': set(['a','c']),
     'e': set(['d'])}

w = {'a': {'b':3, 'c':8, 'e':-4},
     'b': {'d':1, 'e':7},
     'c': {'b':4},
     'd': {'a':2, 'c':-5},
     'e': {'d':6}}


G = Graph(g,w)

In [6]:
W = G.myweight()
print(W)
P = G.myinitialpi()  # when k = 0
print(P)

(node.number :  0 , node.name :  a  )
(node.number :  1 , node.name :  b  )
(node.number :  2 , node.name :  c  )
(node.number :  3 , node.name :  d  )
(node.number :  4 , node.name :  e  )
[[ 0.  3.  8. inf -4.]
 [inf  0. inf  1.  7.]
 [inf  4.  0. inf inf]
 [ 2. inf -5.  0. inf]
 [inf inf inf  6.  0.]]
(node.number :  0 , node.name :  a  )
 node.edge :  {'b': 3, 'c': 8, 'e': -4}
(node.number :  1 , node.name :  b  )
 node.edge :  {'d': 1, 'e': 7}
(node.number :  2 , node.name :  c  )
 node.edge :  {'b': 4}
(node.number :  3 , node.name :  d  )
 node.edge :  {'a': 2, 'c': -5}
(node.number :  4 , node.name :  e  )
 node.edge :  {'d': 6}
[[inf  0.  0. inf  0.]
 [inf inf inf  1.  1.]
 [inf  2. inf inf inf]
 [ 3. inf  3. inf inf]
 [inf inf inf  4. inf]]


In [8]:
Df = floyd_warshall(W)
print(Df)

D array :  
 [[[ 0.  3.  8. inf -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0. inf inf]
  [ 2. inf -5.  0. inf]
  [inf inf inf  6.  0.]]

 [[ 0.  3.  8. inf -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0. inf inf]
  [ 2.  5. -5.  0. -2.]
  [inf inf inf  6.  0.]]

 [[ 0.  3.  8.  4. -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0.  5. 11.]
  [ 2.  5. -5.  0. -2.]
  [inf inf inf  6.  0.]]

 [[ 0.  3.  8.  4. -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0.  5. 11.]
  [ 2. -1. -5.  0. -2.]
  [inf inf inf  6.  0.]]

 [[ 0.  3. -1.  4. -4.]
  [ 3.  0. -4.  1. -1.]
  [ 7.  4.  0.  5.  3.]
  [ 2. -1. -5.  0. -2.]
  [ 8.  5.  1.  6.  0.]]]
---it takes 0.012874364852905273 seconds ---
[[ 0.  1. -3.  2. -4.]
 [ 3.  0. -4.  1. -1.]
 [ 7.  4.  0.  5.  3.]
 [ 2. -1. -5.  0. -2.]
 [ 8.  5.  1.  6.  0.]]


In [9]:
[D,P] = floyd_warshall_with_P(G)
print ("##################  All pair shortest path info ##############################")
print(D)
print(P)

(node.number :  0 , node.name :  a  )
(node.number :  1 , node.name :  b  )
(node.number :  2 , node.name :  c  )
(node.number :  3 , node.name :  d  )
(node.number :  4 , node.name :  e  )
(node.number :  0 , node.name :  a  )
 node.edge :  {'b': 3, 'c': 8, 'e': -4}
(node.number :  1 , node.name :  b  )
 node.edge :  {'d': 1, 'e': 7}
(node.number :  2 , node.name :  c  )
 node.edge :  {'b': 4}
(node.number :  3 , node.name :  d  )
 node.edge :  {'a': 2, 'c': -5}
(node.number :  4 , node.name :  e  )
 node.edge :  {'d': 6}
D array :  
 [[[ 0.  3.  8. inf -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0. inf inf]
  [ 2. inf -5.  0. inf]
  [inf inf inf  6.  0.]]

 [[ 0.  3.  8. inf -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0. inf inf]
  [ 2.  5. -5.  0. -2.]
  [inf inf inf  6.  0.]]

 [[ 0.  3.  8.  4. -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0.  5. 11.]
  [ 2.  5. -5.  0. -2.]
  [inf inf inf  6.  0.]]

 [[ 0.  3.  8.  4. -4.]
  [inf  0. inf  1.  7.]
  [inf  4.  0.  5. 11.]
  [ 2. -1. -5.  0. -